### ISSUE TITLE
Can we have a new release please?

### ISSUE THREAD

**Issue by rajaramsrn** [docusign/docusign-python-client#12]
With the new PRs in, can we please have new release for me to update our app? Thanks!

**Comment by mmallis87** [comment]
There is release coming, mist-likely today, to fix parsing JSON in Python 3.x. However that's the only change that is pending.

Please create issues for actual "issues" and not for asking for new releases. The core team is responsible for the release schedule according to a multitude of factors. Creating an issue won't impact the release schedule.
