### ISSUE TITLE
Cannot add multiple documents to an envelope

### ISSUE THREAD

**Issue by goldjay** [docusign/docusign-python-client#13]
As shown in the tests, I can add a document to an envelope definition

`doc = docusign.Document()
    #base64_doc = base64.b64encode(file_contents).decode("utf-8")
    doc.document_base64 = f
    doc.name = 'TestFile.pdf'
    doc.document_id = '1'
    envelope_definition.documents = [doc]`

However, if I add a second document either by appending the document to the documents list or defining the list with both documents, the second document does not show up. 

Is there only one document allowed, is there another way to add a document or is this a bug?

**Comment by mmallis87** [comment]
@goldjay The SDK does support multiple documents. Please share you code snippet, so we can document the issue, is there is any.

**Comment by LarryKlugerDS** [comment]
Hi @goldjay,

You can add multiple documents to an envelope in a single Envelopes::create call.

See scenario 2 of the [eg-03-python-auth-code-grant example.](https://github.com/docusign/eg-03-python-auth-code-grant)

In particular, see the [eg002 file](https://github.com/docusign/eg-03-python-auth-code-grant/blob/master/app/eg002_signing_via_email.py), lines 150 - 170. They add 3 documents to the envelope.
