### ISSUE TITLE
Default Base url is not working

### ISSUE THREAD

**Issue by chauhoang99** [docusign/docusign-python-client#15]
Hi,

I've tried this SDK on live production Docusign and the host "www.docusign_esign.net" is unable to be accessed. It is hardcoded in the SDK in configuration.py>class Configuration and line 48. My manager checked the PHP SDK and found out there is a different default base url there. So I believe that we are using incorrect default base url for Python and this host is not working.

Could you please kindly review?

Thank you

**Comment by mmallis87** [comment]
@chauhoang99 thank you for reporting this. I fixed the value in my last commit and it should be released as part of the next release.

The hardcoded value is there as a reference and I strongly recommend parsing the base url from the [getUserInfo API response](https://developers.hqtest.tst/esign-rest-api/guides/authentication/user-info-endpoints). The base url depends on which data center your account is hosted in (www, na1, eu, ca, au,....).

Here is a code snippet that shows how to parse the base url dynamically: https://github.com/docusign/docusign-python-client/blob/master/test/unit_tests.py#L66-L80

**Comment by LarryKlugerDS** [comment]
Hi @chauhoang99,

Are you using DocuSign Legacy authentication or DocuSign OAuth authentication?

If the latter then you need to use API call [OAuth::getUserInfo](https://developers.docusign.com/esign-rest-api/guides/authentication/user-info-endpoints)

That API call is not yet supported by the SDK directly but you can call it from Python. If you need the code for doing so, please request.
