### ISSUE TITLE
document cannot be downloaded because file name includes blanks

### ISSUE THREAD

**Issue by juliocarrera** [docusign/docusign-python-client#17]
Downloading a document retrieved by calling envelopes_api.get_document() fails if the file name contains blanks.

**Comment by LarryKlugerDS** [comment]
I apologize for the extreme delay in answering your question. We have reorganized our staff to help prevent these delays in the future. 

I just tried your question with the [Python code example launcher](https://github.com/docusign/eg-03-python-auth-code-grant), and it worked fine to download documents with a space in the file name. 

I suggest that you try the code example launcher yourself, then use its code as a model.

Also, the best place to ask these types of software questions about the DocuSign APIs and SDKs is stackoverflow with the `docusignapi` tag.

Thanks,
Larry
