### ISSUE TITLE
Need more information on how to delete an envelope

### ISSUE THREAD

**Issue by k0pernicus** [docusign/docusign-python-client#19]
I am trying to delete an envelope via the client.
I saw different solutions on the web, especially to move an envelope to the trash folder (or something like that...) but I prefer for now just to delete all documents in a given envelope_id.

Using `delete_documents` with the required parameters: `account_id` and `envelope_id`, the server returns me a 400 error, with the given message:
```
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache', 'Content-Length': '113', 'Content-Type': 'application/json; charset=utf-8', 'X-DocuSign-TraceToken': 'XXXXX, 'Date': 'Fri, 12 Oct 2018 12:16:18 GMT', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: b'{\r\n  "errorCode": "INVALID_REQUEST_BODY",\r\n  "message": "The request body is missing or improperly formatted."\r\n}'
```

Does this method needs more arguments?

**Comment by LarryKlugerDS** [comment]
Hi, 
I apologize for the (very) slow response on this question. We're re-organized to ensure that we answer questions faster.

Is your question still current or have you solved it in the meantime?

Thanks,
Larry
