### ISSUE TITLE
Trouble adding Custom Field Values to Envelope Definition

### ISSUE THREAD

**Issue by ZeroMcMuffin** [docusign/docusign-python-client#20]
I'm having trouble setting the values for the custom fields in my envelope.  There isn't an example for the Python SDK, but I have found others doing something similar in the other SDK's.  Setting the custom_fields property on the envelope definition still allows the initiation of a signing, but the values are not shown to the signer.  I can also see the custom fields when I print the envelope definition.  Here is how I'm doing it (the rest of the omitted code is directly from the readme outside of adding some additional roles):

```python
patient_first_name = TextCustomField(name='PatientFirstName', value='Allen', show='true',
                                     required='true')
patient_last_name = TextCustomField(name='PatientLastName', value='Elks', show='true',
                                    required='true')
custom_fields = CustomFields(text_custom_fields=[patient_first_name, patient_last_name])

envelope_definition.custom_fields = custom_fields
```

[Example from the Java SDK](https://github.com/docusign/docusign-java-client/issues/31)

I can obviously provide the rest of the code if needed.  Thanks!

**Comment by LarryKlugerDS** [comment]
Custom Envelope Fields, by definition are not shown to recipients. Tab fields are shown to recipients.
Custom Envelope Fields enable the developer to sort/categorize/add metadata to envelopes.

To provide information to recipients and signers, create one or more tab fields in the document(s). The fields can be set as read only.
