### ISSUE TITLE
No documentation on private_key_filename.txt

### ISSUE THREAD

**Issue by alamorre** [docusign/docusign-python-client#24]
I'm setting up the python API and I can't see any resources on how to populate the private_key_filename.txt file.

I have a private key, but a private_key_filename.txt file containing just the key will cause errors. Can somebody add some docs on this? Thanks

**Comment by alamorre** [comment]
Nevermind, I found it. There is an example here: https://github.com/docusign/docusign-python-client/blob/master/test/keys/docusign_private_key.txt

**Comment by LarryKlugerDS** [comment]
You can also use the example https://github.com/docusign/eg-01-python-jwt

**Comment by LarryKlugerDS** [comment]
And for more code examples see https://github.com/docusign/eg-03-python-auth-code-grant
