### ISSUE TITLE
the six==1.8.0 requirement in requirements.txt causes dependency issues with other libraries

### ISSUE THREAD

**Issue by mdw123** [docusign/docusign-python-client#29]
Requiring six==1.8.0, which was released in 2014 causes issues with other libraries that require more modern versions of six. Can you consider and test >=1.8.0? that would make things much easier for consumers of this as a dependency. Thanks!

https://pypi.org/project/six/#history

**Comment by dmand** [comment]
Another one affected by this issue here.

Thanks for providing a quick fix for this, @mmallis87.
Can you consider making a quick minor release to ship the fixed version to PyPI?

**Comment by mmallis87** [comment]
@mdw123 @dmand The change was pushed as part of v2.0.1. Please upgrade when you get a chance.

**Comment by dmand** [comment]
Appreciate your support, @mmallis87

**Comment by mdw123** [comment]
Works for me, thanks for the release.

**Comment by mmallis87** [comment]
Thank you guys for your valuable input and stay tuned for the incoming support of [eSignature API v2.1](https://www.docusign.com/blog/dsdev-docusign-esignature-api-v21-api-unveiled)!
