### ISSUE TITLE
Geting an error from the source code

### ISSUE THREAD

**Issue by osimuka** [docusign/docusign-python-client#34]
https://github.com/docusign/docusign-python-client/blob/37245f757fe40228ff311d07f7fa0ea5877c15bd/docusign_esign/client/api_client.py#L733

TypeError: the JSON object must be str, not 'bytes'

Can this be fixed please ?

Using Python 3.5.0

Possible solution:
```response_data = json.loads(response.data.decode('utf-8'))```

**Comment by osimuka** [comment]
```class CustomDocusignAPiClient(docusign.ApiClient):

    def request(self, method, url, **kwargs):
        response = super().request(method, url, **kwargs)

        r = RESTResponse(response)
        r.data = r.data.decode('utf8', 'replace')
        return r```

**Comment by LarryKlugerDS** [comment]
Hi @osimuka ,

What is happening currently? 
When the TypeError is raised, is there a work-around? 
Are you able to use the SDK with Python 3.5?

Thank you for the bug report.

**Comment by osimuka** [comment]
> Hi @osimuka ,
> 
> What is happening currently?
> When the TypeError is raised, is there a work-around?
> Are you able to use the SDK with Python 3.5?
> 
> Thank you for the bug report.

So when you call the self.request() in python3 it throws the type error ```TypeError: the JSON object must be str, not 'bytes'```

My work around was to do subclass the ApiClient class and modify the return value for response.data ```
class CustomDocusignAPiClient(docusign.ApiClient):

    def request(self, method, url, **kwargs):
        response = super().request(method, url, **kwargs)

        r = RESTResponse(response)
        r.data = r.data.decode('utf8', 'replace')
        return r
```

**Comment by osimuka** [comment]
A fix for this issue is to not call ```self.request``` directly in any of the methods that require requests, instead call ```self. call_api``` as it handles this problem

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I've filed DCM-3470

**Comment by harsharahul** [comment]
Hi @osimuka,

I am looking into the SDK and I invoked  `response_data = json.loads(response.data)` function in api_client.py using `request_jwt_application_token` and also `request_jwt_user_token` functions in Python 2.7, 3.5, 3.7 versions. I don't have any problems getting the data or any exceptions raised. The tests are passing successfully. 

Is there any specific environment that you have, that I am missing that might have caused the issue? Let me know.

-Harsha

**Comment by LarryKlugerDS** [comment]
Hi @osimuka ,
Our DocuSign engineer, @harsharahul , was unable to reproduce the problem. 

If you'd like us to look at it again, please submit a test case that fails with the current version of the Python SDK.

Thank you for your help,
Larry

**Comment by cspropertygroup** [comment]
When I run this command in python 3.5: 
```
ContractSigner.api_client = docusign.APiClient(
            base_path=settings.DOCUSIGN_BASE_URL,
            oauth_host_name=settings.DOCUSIGN_OAUTH_BASE_HOSTNAME
        )
```
I get the error message: `TypeError: the JSON object must be str, not 'bytes'`
