### ISSUE TITLE
Python Signing Groups API

### ISSUE THREAD

**Issue by dogrultan** [docusign/docusign-python-client#35]
I would like to send a group of signers the same envelope containing the same document. I am achieving this by following [this](https://developers.docusign.com/esign-rest-api/code-examples/quickstart-request-signature-email) tutorial and by changing `routing_order`, but I would like to send the e-mail at the same time to all recipients and only one signature is needed. I've found [SigningGroups](https://developers.docusign.com/esign-rest-api/reference/signinggroups/signinggroups/), which seems like what I'm trying to use, but I couldn't find any resources on how to do this using [Python API](https://github.com/docusign/docusign-python-client). Can you provide any examples or snippents? Thank you!

**Comment by dogrultan** [comment]
I am sharing a sample code snippet which worked for me:

```
def set_up_docusign_envelope(database_table, user, base64_file_content):
    document = Document(
        document_base64=base64_file_content,
        name=f"{database_table}",
        file_extension='pdf',
        document_id=f"{database_table.id}"
    )

    user = user.profile

    # Create the signer recipient model
    signer = Signer(email=user.email, name=f"{user.first_name} {user.last_name}", recipient_id=f"{user.id}", routing_order=f"{user.id}")

    # Create a sign_here tab (field on the document)
    sign_here = SignHere(
        document_id=f"{database_table.id}", anchor_string="Signature:", recipient_id=f"{user.id}", anchor_x_offset="0.5", anchor_y_offset="0.5", anchor_units="inches", anchor_ignore_if_not_present=False, tab_label='SignHereTab',
    )

    # Add the tabs model (including the sign_here tab) to the signer
    signer.tabs = Tabs(sign_here_tabs=[sign_here])

    webhook_url = 'https://webhookurl.com/api/docusign-webhook/'

    event_notification = EventNotification(
        url=webhook_url,
        logging_enabled="true",
        require_acknowledgment="true",
        use_soap_interface="false",
        include_certificate_with_soap="false",
        sign_message_with_x509_cert="false",
        include_documents="true",
        include_envelope_void_reason="true",
        include_time_zone="true",
        include_sender_account_as_custom_field="true",
        include_document_fields="true",
        include_certificate_of_completion="true",
        envelope_events=[
            EnvelopeEvent(
                envelope_event_status_code="Completed",
                include_documents="false"
            ),
        ]
    )

    # Next, create the top level envelope definition and populate it.
    envelope_definition = EnvelopeDefinition(
        email_subject=f"Please sign {database_table} document",
        documents=[document],
        recipients=Recipients(signers=[signer]),
        status="sent",
        event_notification=event_notification
    )

    return envelope_definition
```

It sends a POST request when given event occurs, with a body in text/xml content type which you can parse using a library like BeautifulSoup.

[This](https://developers.docusign.com/esign-rest-api/code-examples/webhook-status) was also helpful.

If you have any questions, you can ask from here:)

**Comment by harsharahul** [comment]
Hi @dogrultan,

Thank you very much for sharing the code snippet which worked out for you. We will look into the snippet and if possible add similar use case to the test cases for future release. If there is no other comment, would you mind closing this issue?

-Harsha

**Comment by dogrultan** [comment]
Sure, thank you.
