### ISSUE TITLE
Documents with the same file name can collide when downloaded

### ISSUE THREAD

**Issue by yulianovdey** [docusign/docusign-python-client#41]
Hello!

We ran into an issue where downloading a document using `get_document` and then reading it sometimes returns the wrong contents if we also downloaded another document with the same name, even if it's for a different envelope. [__deserialize_file](https://github.com/docusign/docusign-python-client/blob/b7f341146255d1171bd9b89668477340c1b2308f/docusign_esign/client/api_client.py#L568) might be the culprit:

```
path = os.path.join(os.path.dirname(path), filename)
```

It looks like the client doesn't use the file name returned from `mkstemp` and appends the name of our file to the temp file's directory to create the path instead. If the path already exists, `open(path, "wb")` just truncates it before writing new content.

**Comment by WilliamWCYoung** [comment]
we just got burnt by this..

**Comment by LarryKlugerDS** [comment]
DCM-3631 is in code review

**Comment by harsharahul** [comment]
A fix for this has been released as part of v3.1.0+ for apiv2.1 family and v2.2.0+ for apiv2.0
