### ISSUE TITLE
configure_jwt_authorization_flow() does not honor the explicit OAuth grants via oauth URL. Throws 'Consent Required" error

### ISSUE THREAD

**Issue by rajaramsrn** [docusign/docusign-python-client#5]
Despite granting access by logging in using the URL given by oauth_login_url below, the subsequent "api_client.configure_jwt_authorization_flow" call always results in 'consent_required' error. The corresponding integrator key is set up with right redirect URI and key pair (of which I use the private key as private_key_filename below). However, using the test parameters (user_id, integrator key, etc) from the unit_test works fine. There is some other nuance or detail that is explicitly missing in the example or prerequisites. Note that the account is not associated to any Organization yet. I am not yet there. But I would expect this basic flow to work as is.

```
oauth_login_url = api_client.get_jwt_uri(integrator_key, redirect_uri, oauth_base_url)

print(oauth_login_url)

       https://account-d.docusign.com/oauth/auth?response_type=code&client_id=<integrator_key>&scope=signature%2Bimpersonation&redirect_uri=https%3A%2F%2Fwww.docusign.com%2Fapi

api_client.configure_jwt_authorization_flow(private_key_filename, oauth_base_url, integrator_key, user_id, 3600)

  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/userme/projects/docudocu/lib/python2.7/site-packages/docusign_esign/api_client.py", line 118, in configure_jwt_authorization_flow
    post_params=self.sanitize_for_serialization({"assertion": assertion, "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer"}))
  File "/Users/userme/projects/docudocu/lib/python2.7/site-packages/docusign_esign/api_client.py", line 418, in request
    body=body)
  File "/Users/userme/projects/docudocu/lib/python2.7/site-packages/docusign_esign/rest.py", line 244, in POST
    body=body)
  File "/Users/userme/projects/docudocu/lib/python2.7/site-packages/docusign_esign/rest.py", line 200, in request
    raise ApiException(http_resp=r)

    docusign_esign.rest.ApiException: (400)
    Reason: Bad Request
    HTTP response headers: HTTPHeaderDict({'X-DocuSign-Node': 'CH1DFE2', 'Content-Length': '28', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Content-Security-Policy-Report-Only': "script-src 'unsafe-inline' 'unsafe-eval' 'self';style-src 'unsafe-inline' 'self';img-src https://docucdn-a.akamaihd.net/ 'self';font-src 'self';connect-src 'self';object-src 'none';media-src 'none';frame-src 'none';frame-ancestors 'none';report-uri /client-errors/csp", 'X-XSS-Protection': '1; mode=block', 'X-DocuSign-TraceToken': 'b009b0a6-19ad-4e58-844e-76fc5b509cbb', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Date': 'Wed, 29 Nov 2017 22:52:10 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'X-AspNetMvc-Version': '5.2'})
    HTTP response body: {"error":"consent_required"}

```

(Note: Also asked a question here https://stackoverflow.com/questions/47563725/getting-consent-required-error-despite-successful-permission-grant-using-oauth )

**Comment by mmallis87** [comment]
@rajaramsrn Looks like Amir and Larry are trying to help you S.O. please don't forget to close this issue once they solve your issue. I will make sure to post a summary of the solution here, once the issue if resolved.

**Comment by rajaramsrn** [comment]
@mmallis87 Please review my PR and S.O. response for this issue. Thank you.

**Comment by rajaramsrn** [comment]
If there are plans to fix this issue of delimiter in get_jwt_uri() utility much more comprehensively along with the CI test issues, I am fine to ignore my PR. But I seriously need this capability to generate and suggest the correct 'Grant requesting URL with 2 claims' to my app users as per the [JWT OAUTH](https://docs.docusign.com/esign/guide/authentication/oa2_jwt.html#creating-the-jwt-token) doc. Either way please let me know what your release plans are to make such fixed pip image Thanks in bunch.

**Comment by mmallis87** [comment]
The PR was merged and a new version will be released in PyPi (pip) soon. I will close this once it's shipped.

**Comment by mmallis87** [comment]
Shipped: https://pypi.python.org/pypi/docusign-esign/1.0.2 @
