### ISSUE TITLE
Calling EnvelopesApi#update_document_tabs returns an error

### ISSUE THREAD

**Issue by yulianovdey** [docusign/docusign-python-client#51]
Hello!

I'd like to figure out why the following code returns an error from the server:

```
envelope_tabs = envelopes_api.get_document_tabs(ACCOUNT_ID, document_id, envelope_id)

envelopes_api.update_document_tabs(ACCOUNT_ID, document_id, envelope_id, tabs=envelope_tabs)
```

The following error gets returned:

```
{"errorCode":"INVALID_TAB_OPERATION","message":"The Tab specified is not valid for the requested operation. Updated tabs must all be Strikethrough or SmartSection tabs if you\'re not specifying a valid recipient."}
```

In reality I'm trying to modify some tabs before doing the update, but I removed that code to eliminate that as the source of the issue before reproducing this.

I understand that I can also use `EnvelopesApi#update_tabs ` to separately update tabs for each recipient, but is there a way to call `update_document_tabs` and update everything at once?

**Comment by LarryKlugerDS** [comment]
The [EnvelopeDocumentTabs::update (update_document_tabs)](https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeDocumentTabs/update) method takes a different data structure argument than what is returned from the [EnvelopeDocumentTabs::get (get_document_tabs)](https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeDocumentTabs/get)

If you fill in the additional information into the request to the update, it should work ok.

This type of question about the API methods is best asked on StackOverflow using the `docusignapi` tag. Thank you.

**Comment by yulianovdey** [comment]
For posterity, the data structure argument is actually the same, at least according to the API reference, and I can't find any additional fields the request might need. It might be a bug with this endpoint. More details in the SO thread [here](https://stackoverflow.com/questions/59865511/calling-envelopesapiupdate-document-tabs-returns-an-error).

**Comment by InbarGazit** [comment]
The bug in our internal system is marked as EC-2079. We will update you when we have news.
