### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by ssingh09** [docusign/docusign-python-client#56]
in docusign version 3.1.0 , pthon version 3.5 and 3.6  in sandbox mode .
getting following error
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //account-d.docusign.com/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77f6c8dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by LarryKlugerDS** [comment]
What are you trying to do? JWT Grant authentication? Please see the [eg-01-python-jwt](https://github.com/docusign/eg-01-python-jwt) code example. 

Thank you,
Larry

**Comment by ssingh09** [comment]
i am trying JWT Grant Authentication in sandbox mode. i have tried [https://github.com/docusign/eg-01-python-jwt](eg-01-python-jwt ) but facing same issue.

**Comment by LarryKlugerDS** [comment]
eg-01-python-jwt works, I just tried it. Please ask for help in getting eg-01-python-jwt working on stackoverflow.com with tag `docusignapi` and we'll help you there. 

The issue to be solved is for you to get the example working, then build from there. This is not an issue with the SDK itself.

Check that you are entering the private key correctly. If you are using the Python .ini system note that the second and subsequent lines need to have a single space prepended. See the example's ds_config.ini for more info.
