### ISSUE TITLE
jwt request token issue 

### ISSUE THREAD

**Issue by ssingh09** [docusign/docusign-python-client#57]
docusign version 3.1.0 , pthon version 3.5 and 3.6 in sandbox mode .
getting following error
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //account-d.docusign.com/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa77f6c8dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

i have followed the curl request using following url [JSON Web Token (JWT) Grant
](https://developers.docusign.com/esign-rest-api/v2/guides/authentication/oauth2-jsonwebtoken)
i got a access token 
got an application token and while passing in auth giving me 401(401 UNAUTHORIZED
) error
[postman](https://ibb.co/LQtzF69)
[token image](https://ibb.co/t3YMkr2)

`>claim = {"iss": '4556e2f7-4a3d-41f9-a0c3-18535a28ab2a', "aud": 'account-d.docusign.com', "iat": now, "exp": later, "scope": " ".join(scopes)}
        token = jwt.encode(payload=claim, key=pkey, algorithm='RS256').decode("utf-8")`
i getting application token using above code but when i pass all the required parameter i got {"error":"invalid_grant","error_description":"no_valid_keys_or_signatures"} but when i pasted my jwt  token in jwt.io with my public and privte key its says signature verified.
 
[tonen image](https://ibb.co/2yKXNCW)
[jwt io image](https://ibb.co/cFTk6R1)

**Comment by LarryKlugerDS** [comment]
[eg-01-python-jwt](https://github.com/docusign/eg-01-python-jwt) demonstrates how to use the JWT flow from Python3. That example works, so please first install / configure it on your own system so it works for you.

Then use it as a model for your own application.

In the future, please use StackOverflow with tag `docusignapi` when you have an application question. Thank you.

**Comment by Bernard-Vesy** [comment]
The concept is to generate a key with 3 elements (Header RS256 Algorith, the Payload Data that contains the application date and token validity and the private and public key. On the site jwt.io we will put all this information and the site will retour an Base64 Key we can further entered on 

Open the JWT.IO site  jwt.io

1.	Choose Algorithm RS256 on the top

For the second Pane : “Payload: Data”

https://admindemo.docusign.com/apps-and-keys 
**iss** : <integration key>

The integration key (also known as client ID) of the application.

**sub** : The User ID of the user to be impersonated. 
(The person granting permission must have a DocuSign user account.)
The provided User ID must be in GUID (not email) format. You can look up a user’s GUID from their email using the users.list method.
Note: If you don’t already have the User ID of the user to act on behalf of, you can obtain it by completing the Authorization Code Grant flow begun in the Request the authorization code step.

https://admindemo.docusign.com/apps-and-keys -> Apps and Keys -> 

**aud** : The URI of the authentication service instance to be used.
For demo environments, use account-d.docusign.com.
For production environments, use account.docusign.com.

Important: Do not include https:// in the aud value!

**iat** : The date-time when the JWT was issued
in Unix epoch format. You must include an iat value when creating a JWT, typically set to the current time.

You can convert a date to linux epoch format with the following link : https://www.epochconverter.com/

 

**exp**: The date-time when the JWT assertion will expire

 in Unix epoch format. Defaults to one hour from the value of iat and cannot be set to a greater value. You must include an exp value when creating a JWT.
Use the epoch https://www.epochconverter.com/ 

⚠ Please note that this value must not be too far in time, in our example we are using 14 years of validity.

 

**scope** : The scopes to request. In our example “signature impersonation”. 
All the scopes are defined on the following site https://developers.docusign.com/platform/auth/reference/scopes/ 


{
"iss":"ea670856-xxxx-xxxx-99bd-80560d323639",
"sub":"917c9fc5-xxxx-xxxx-8a28-87e7ede3b8ac",
"aud":"account-d.docusign.com",
"iat": 1628496664,
"exp":1912493464,
"scope":"signature impersonation"
}



For the Pane “Verify Signature”
https://admindemo.docusign.com/apps-and-keys -> Actions -> Edit

 … -> Click on “Generate RSA” 
 

Select the Public and Paste it on the section 
 
And make the same for the public key. If everything is OK, you must have the Tag “Signature Verified” at the left of the document, see the picture bellow.

For the final step, you obtain the key for stating using the API


TEST THE API WITH POSTMAN WITH THE KEY PREVIOUSLY GENERATED 

Go to Postman

1.	https://www.postman.com/use-cases/api-testing-automation/ 
2.	Sign in (for me with my google account)
3.	You must fille the following values

1. Select “Post”
2. Put the API Value : https://account-d.docusign.com/oauth/token  
3. Click on the “Body” section
4. Add the key “grant_type” 
5. Add the value “urn:ietf:params:oauth:grant-type:jwt-bearer” for the key “grant_type”
6. Add the key “assertion”
7. Add the generate value from the site jwt on the previous steps 
      

8. Finally Click on Send for obtain the “access_token” necessary the the further call.
