### ISSUE TITLE
require_id_lookup does nothing

### ISSUE THREAD

**Issue by strickon** [docusign/docusign-python-client#84]
It appears that when id_check_configuation_name is set to a value (ex. ID Check), require_id_lookup does nothing to enable or disable ID check.  According to the docs, you need both.  The result of seeing ID Check is independent of any value for require_id_lookup  when I set id_check_configuration_name, require_id_lookup can be set to "true" or "false" or not appear at all,  and I get the same result of having id check.  Am I interpreting the documentation wrong?  Has the api changed? Is this a bug?

**Comment by LarryKlugerDS** [comment]
Sounds like you want to use ID Verification. 

To do so: 

````
"recipients": {
      "signers": [
        {
          "email": "email",
          "name": "name",
          "recipientId": "1",
          "clientUserId": "1000",
          "identityVerification": {
            "workflowId": "1234-56789-xxx"
          },
          "tabs": {
            "signHereTabs": [
              {
                "anchorString": "/sig1/",
                "anchorXOffset": "20",
                "anchorUnits": "pixels"
              }
            ]
          }
        }
      ]
    }
````

`idCheckConfigurationName` does not appear to be needed any longer. (I'm 99% sure of this.)

`requireIdLookup` is not needed.

Can you give the url where the incorrect information is provided? I'll get it updated. 

Thanks,
Larry

**Comment by strickon** [comment]
There are two places where this shows up.

https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeRecipients/ <https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeRecipients/>

https://github.com/docusign/docusign-python-client/blob/master/docusign_esign/models/signer.py <https://github.com/docusign/docusign-python-client/blob/master/docusign_esign/models/signer.py>


I am not using workflows and want to specify on an envelope by envelope basis.  So maybe it is just that requireIDLookup is deprecated and no longer needed  and is that same logic is simply keyed off the presence of IDCheckConfigurationName.


-Josh

----------------------------------------------
Joshua Strickon, PhD
The Ocean View Lab, LLC
330 Harbor Ct.
Key Biscayne,  FL  33149
917.517.9874
strickon@oceanviewlab.com
www.oceanviewlab.com

**Comment by LarryKlugerDS** [comment]
Thank you. I have filed internal bug DEVDOCS-3549
